### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by rogueturnip** [heroui-inc/next-app-template#9] opened 2023-11-11 18:41 UTC
Thanks for the great starting template.  I'm running into a strange issue.  I've pretty much matched line by line the setup and the navbar is functioning oddly for me.
![image](https://github.com/nextui-org/next-app-template/assets/7782364/0f0bf2b1-6a8b-404a-9d9e-9a31ad11de50)

I don't get the menu icon and when I tap I see the Open/close text toggle but it's not opening the menu.

Any thoughts?

**Comment by isaacdarcilla** [comment] 2023-11-29 07:42
Do you have updates on this? If fixed, how did you fixed this?

**Comment by realejeh** [comment] 2024-01-11 12:17
same issue here...

**Comment by isaacdarcilla** [comment] 2024-01-11 12:38
> same issue here...

@DevIsraelHub You might want to use `pnpm` to install this. It worked for me.

**Comment by realejeh** [comment] 2024-01-12 17:19
@isaacdarcilla thanks 👍

**Comment by wingkwong** [comment] 2024-05-21 08:19
Closing - not able to reproduce

**Closed as not planned by wingkwong** 2024-05-21 08:19 UTC
